web/api/urls.py
from django.urls import path, include
from . import views

from rest_framework import routers
from . import views, models

router = routers.DefaultRouter()
router.register(r'pizzas', views.PizzaViewSet)
router.register(r'usuarios', views.UserViewSet)
router.register(r'comentarios', views.ComentarioViewSet)
router.register(r'direcciones', views.DireccionViewSet)

app_name = 'api'

urlpatterns = [
  path('',include(router.urls)),
  path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

web/pizzeria/urls.py
from django.urls import path

from . import views

app_name = 'pizzeria'

urlpatterns = [
    path('', views.index, name='index'),
    path('nuestras_pizzas', views.nuestras_pizzas, name='nuestras_pizzas'),
    path('contacto', views.contacto, name='contacto'),
    path('dejar_comentario', views.dejar_comentario, name='dejar_comentario'),
    path('carrito', views.carrito, name = 'carrito'),
    #en esta ruta le pasamos el parametro del id de comentario
    path('editar_comentario/<int:id_comentario>', views.editar_comentario, name='editar_comentario'),
    path('borrar_comentario/<int:id_comentario>', views.borrar_comentario, name='borrar_comentario'),
    path('mostrar_info_pizza/<int:id_pizza>', views.mostrar_info_pizza, name = 'mostrar_info_pizza'),
]

web/usuarios/urls.py
from django.urls import path, include
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    #pagina de registro
    path('registrarse/', views.registrarse, name='registrarse'),
    path('perfil/', views.perfil, name='perfil'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pizzeria.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

web/pizzeria/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Pizza(models.Model):
    nombre = models.CharField(max_length = 30)
    precio = models.FloatField()

    def __str__(self):
        return self.nombre

class Direccion(models.Model):
    direccion = models.CharField(max_length=60)
    poblacion = models.CharField(max_length=20)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.direccion

class Comentario(models.Model):
    comentario = models.CharField(max_length=1000)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

class Pedido(models.Model):
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete = models.CASCADE)

class Cesta(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE, primary_key=True)
    pedido = models.ForeignKey(Pedido, on_delete = models.CASCADE)





#insertar    
#pizza = Pizza(nombre='Pizza barbacoa', precio=9.9)

web/pizzeria/forms.py
from django import forms
from .models import Comentario

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        #los campos que apareceran en el formulario
        fields = ['comentario']

web/pizzeria/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Comentario
from .forms import ComentarioForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
from django.http import HttpResponse

#este metodo devuelve todas las pizzas
#almacenadas en SQLite
def query_pizzas():
    pizzas = Pizza.objects.all()
    return pizzas

def index(request):
    pizzas = query_pizzas()
    context = {'pizzas': pizzas}
    return render(request, 'pizzeria/index.html')

def nuestras_pizzas(request):
    #selecciona todas las pizzas en la bbdd sqlite
    pizzas = query_pizzas()
    context = {'pizzas': pizzas}
    #se las pasamos al html
    return render(request, 'pizzeria/nuestras_pizzas.html', context)

def mostrar_info_pizza(request, id_pizza):
    #pizza seleccionada (requested)
    req_pizza = Pizza.objects.get(id = id_pizza)
    pizzas = Pizza.objects.all()
    context = {'req_pizza': req_pizza,'pizzas':pizzas}
    return render(request, 'pizzeria/nuestras_pizzas.html', context)

def contacto (request):
    return render(request, 'pizzeria/contacto.html')

@login_required
def dejar_comentario(request):
    if request.method != 'POST':
        #seleccionamos los comentarios
        comentarios = Comentario.objects.all()
        form = ComentarioForm()
    else:
        form = ComentarioForm(data = request.POST)
        if form.is_valid():
            #le añadimos el usuario al comentario nuevo
            nuevo_comentario = form.save(commit=False)
            nuevo_comentario.usuario = request.user
            nuevo_comentario.save()
            return redirect('pizzeria:index')
    context = {'form': form, 'comentarios': comentarios}
    return render(request, 'pizzeria/dejar_comentario.html', context)


#REVISAR MAS TARDE
@login_required
def editar_comentario(request, id_comentario):
    comentario = Comentario.objects.get(id = id_comentario)
    if comentario.usuario !=request.user:
        raise Http404
    if request.method != 'POST':
        #recogemos todos los comentario para mostrarlos
        comentarios = Comentario.objects.all()
        form =ComentarioForm()
        form.comentario = comentario.comentario
    else:
        if form.is_valid():
            comentario.comentario = form.comentario
            comentario.update()
    context = {'form': form, 'comentarios': comentarios}
    return render(request, 'pizzeria/dejar_comentario.html', context)

    
@login_required
def borrar_comentario(request, id_comentario):
    comentario = Comentario.objects.get(id = id_comentario)
    if comentario.usuario != request.user:
        raise Http404

    #metodo post
    #html no acepta ni DELETE ni PUT
    if request.method =='POST':
        comentario.delete()
        return redirect('pizzeria:dejar_comentario')


def carrito(request):
    return render(request, 'pizzeria/carrito.html')
    
   
        

web/pizzeria/templates/pizzeria/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'pizzeria/styles.css' %}">
    
    <title>Pizzeria</title>
</head>
<body>
    <nav class="navbar">
        <div class="brand-title">Pizzeria</div>
        <a href="#" class="toggle-button">
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
        </a>
        <div class="navbar-links">
          <ul>
            <li><a href="{% url 'pizzeria:index' %}">Inicio</a></li>
            <li><a href="{% url 'pizzeria:nuestras_pizzas' %}">Nuestras pizzas</a></li>
            <li><a href="{% url 'pizzeria:dejar_comentario' %}">Comentarios</a></li>
            {% if user.is_authenticated %}
                <li><a class="usuario" href="{% url 'usuarios:perfil' %}">{{ user.username }}</a></li>
            {% else %}
                <li><a class="usuario" href="{% url 'usuarios:login' %}">Login</a></li>
            {% endif %}
            <li><a class="usuario" href="{% url 'pizzeria:carrito' %}">Carrito</a></li>
          </ul>
        </div>
      </nav>

     

    {% block content %}
    {% endblock content%}

    <script src="{% static 'pizzeria/scripts.js' %}"></script>

    <footer>
        <p>Autor: Imanol Ortiz</p>
    </footer>
    
</body>
</html>

web/pizzeria/templates/pizzeria/carrito.html
{% extends 'pizzeria/base.html' %}
{% block content %}

<p>Carrito</p>

{% endblock content%}

web/pizzeria/templates/pizzeria/contacto.html
{% extends 'pizzeria/base.html' %}
{% block content %}

<p>Contactanos</p>


<div class="formulario">
    <form method="POST" action="{% url 'pizzeria:deja_comentario' %}">
        <!--
        <label>Correo:</label>
        <input type="text" name="correo" id="correo" required/>
        <label>Comentario</label>
        <textarea rows=5 cols=10 name="comentario" required></textarea>
        <input type="submit" value="Enviar"/>
        -->



    </form>
</div>

{% endblock content%}

web/pizzeria/templates/pizzeria/copia_nav_viejo.html
<nav class="navegador">
    <ul id="elementos">
        <li class="boton_responsive"><button onclick="mostrarOcultar()">Responsive</button></li>
        <li><a href="{% url 'pizzeria:index' %}">Inicio</a></li>
        <li><a href="{% url 'pizzeria:nuestras_pizzas' %}">Nuestras pizzas</a></li>
        <li><a href="{% url 'pizzeria:contacto' %}">Contacto</a></li>
        <li><a href="{% url 'pizzeria:dejar_comentario' %}">Deja comentario</a></li>
        {% if user.is_authenticated %}
            <li><a class="usuario" href="{% url 'usuarios:perfil' %}">{{ user.username }}</a></li>
        {% else %}
            <li><a class="usuario" href="{% url 'usuarios:login' %}">Login</a></li>
        {% endif %}
        <li><a class="carrito" href="#">Carrito</a></li>
    </ul>
</nav>

web/pizzeria/templates/pizzeria/dejar_comentario.html
{% extends 'pizzeria/base.html' %}
{% block content %}

<p>Seccion de comentarios</p>

{% for comentario in comentarios %}

<div class="comentario">
    <p class="c_usuario">{{comentario.usuario}}</p>
    <p class="texto">{{comentario.comentario}}</p>
    <p class="fecha">{{comentario.fecha_publicacion}}</p>
    {%if comentario.usuario == request.user %}
        <form method="POST" action="{% url 'pizzeria:editar_comentario' comentario.id %}">
            {% csrf_token %}
            <input type="submit" value="Editar comentario"/>
        </form>
        <form method="POST" action="{% url 'pizzeria:borrar_comentario' comentario.id %}">
            {% csrf_token %}
            <input type="submit" value="Borrar"/>
        </form>  
    {% endif %}
</div>

{% empty %}
    <p>No hay comentarios</p>
{% endfor %}


<div class="formulario">
    <form method="POST" action="{% url 'pizzeria:dejar_comentario' %}">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Enviar"/>
    </form>
</div>

{% endblock content%}

web/pizzeria/templates/pizzeria/index.html
{% extends 'pizzeria/base.html' %}
{% block content %}

<div class="mas_vendidas">
    <h2>Pizzas mas vendidas</h2>
    {% for pizza in pizzas %}
        <div class="carta_pizza">
            <div class="titulo">
                <p>{{pizza}}</p>
            </div>
            <!--Cargamos la url static-->
            {% load static %}
            <div class="imagen">
                <img src="{% static 'pizzeria/pizza.jpg' %}" alt="pizza">
            </div>
            <form action="{% url 'pizzeria:mostrar_info_pizza' pizza.id %}">
                <button onclick="mostrar()">Mas info</button>
            </form>
        </div>
    {% empty %}
        <p>No hay pizzas</p>
    {% endfor %}
</div>

{% endblock content%}

web/pizzeria/templates/pizzeria/nuestras_pizzas.html
{% extends 'pizzeria/base.html' %}
{% block content %}


{% for pizza in pizzas %}
    <div class="carta_pizza">
        <div class="titulo">
            <p>{{pizza}}</p>
        </div>
        <!--Cargamos la url static-->
        {% load static %}
        <div class="imagen">
            <img src="{% static 'pizzeria/pizza.jpg' %}" alt="pizza">
        </div>
        <form action="{% url 'pizzeria:mostrar_info_pizza' pizza.id %}">
            <button onclick="mostrar()">Mas info</button>
        </form>
    </div>

    <div class="pizza" id="pizza">
        <div class="pizza_contenidos">
            <span class="close">&times;</span>
            <p>Precio {{pizza.precio}}</p>
            <button>Añadir al carrito</button>
        </div>
    </div>



{% empty %}
<p>No hay pizzas</p>

{% endfor %}

{% endblock content%}